version: "3.8"

services:

    app:
        image: wisgoon-scraper-api:1.0.0
        container_name: wisgoon-scraper-api
        build: ./app
        restart: on-failure
        expose:
          - 8000
        volumes:
          - ./app/:/usr/src/app/
          - ./static/:/usr/src/static/
          - ./media/:/usr/src/media/
        depends_on:
          - postgres
          - redis
          - nginx
          #- rabbitmq
        # env_file:
        #     - .env

    postgres:
        image: postgres:15.1-alpine
        ports:
          - 5432:5432
        environment:
            POSTGRES_PORT: 5432
            POSTGRES_DB: "wisgoon_scraper"
            POSTGRES_USER: "wisgoon_scraper"
            POSTGRES_PASSWORD: "wisgoon_scraper"
        volumes:
            - postgres-data:/var/lib/postgresql/data/

    redis:
        image: redis:6.2.7-alpine
        ports:
            - 6379:6379 
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - redis-data:/data

    nginx:
        build: ./nginx
        container_name: nginx
        restart: on-failure
        ports:
            - 80:80
        volumes:
            - ./static/:/static/
            - ./media/:/media/

    # rabbitmq:
    #     image: rabbitmq:3.11.8-alpine
    #     ports:
    #         - "5672:5672"
    #     environment:
    #         HOSTNAME: rabbitmq
    #         RABBITMQ_DEFAULT_USER: wisgoon_scraper
    #         RABBITMQ_DEFAULT_PASS: wisgoon_scraper
    #         RABBITMQ_DEFAULT_VHOST: wisgoon_scraper
    #     volumes:
    #         - rabbitmq-data:/var/lib/rabbitmq

volumes:
    postgres-data:
    redis-data:
    # rabbitmq-data:
