# Generated by Django 4.1.6 on 2023-02-08 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('username', models.CharField(db_index=True, max_length=300, unique=True, verbose_name='username')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'pages',
                'db_table': 'Page',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('source_id', models.PositiveBigIntegerField(db_index=True, unique=True, verbose_name='source_id')),
                ('title', models.TextField(blank=True, verbose_name='title')),
                ('text', models.TextField(blank=True, verbose_name='text')),
                ('source_created', models.DateTimeField(verbose_name='source_created')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.page', to_field='username', verbose_name='page')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'db_table': 'Post',
                'ordering': ['-source_created'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('url', models.URLField(verbose_name='url')),
                ('is_main', models.BooleanField(default=False, verbose_name='is_main')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_set', to='core.post', to_field='source_id', verbose_name='post')),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'media',
                'db_table': 'Media',
            },
        ),
    ]
